## Relatorio de Analise V

## Tratamento de Dados Faltantes

In [4]:
import pandas as pd

data = pd.read_csv('data/aluguel_residencial.csv', sep = ';')
data

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
4,5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
5,6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0
6,7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0
7,9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
8,10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
9,11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
10,12,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,0.0
11,13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
12,14,Casa de Condomínio,Taquara,3,1,1,115,2000.0,0.0,0.0
13,15,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
14,16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
15,17,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
16,18,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,0.0
17,19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,0.0
18,20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,0.0
19,21,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
20,22,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
21,23,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
22,24,Casa,Campo Grande,4,1,2,400,12000.0,0.0,0.0
23,25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,0.0
24,26,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
25,27,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
26,28,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,0.0
27,29,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
28,30,Quitinete,Copacabana,1,0,0,27,1300.0,380.0,53.0
29,31,Apartamento,Jardim Oceânico,3,3,1,200,3500.0,1780.0,496.0
...,...,...,...,...,...,...,...,...,...,...
21796,22550,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
21797,22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
21798,22552,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
21799,22553,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
21800,22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
21801,22555,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,0.0
21802,22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,0.0
21803,22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
21804,22558,Casa,Centro,5,0,1,160,5000.0,0.0,80.0
21805,22559,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
21806,22560,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
21807,22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
21808,22562,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
21809,22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
21810,22564,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
21811,22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
21812,22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
21813,22567,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
21814,22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,0.0
21815,22569,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
21816,22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
21817,22571,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
21818,22572,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
21819,22573,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,0.0
21820,22574,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
21821,22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
21822,22576,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
21823,22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
21824,22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
21825,22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0

In [5]:
data.isnull()

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
21796,False,False,False,False,False,False,False,False,False,False
21797,False,False,False,False,False,False,False,False,False,False
21798,False,False,False,False,False,False,False,False,False,False
21799,False,False,False,False,False,False,False,False,False,False
21800,False,False,False,False,False,False,False,False,False,False
21801,False,False,False,False,False,False,False,False,False,False
21802,False,False,False,False,False,False,False,False,False,False
21803,False,False,False,False,False,False,False,False,False,False
21804,False,False,False,False,False,False,False,False,False,False
21805,False,False,False,False,False,False,False,False,False,False
21806,False,False,False,False,False,False,False,False,False,False
21807,False,False,False,False,False,False,False,False,False,False
21808,False,False,False,False,False,False,False,False,False,False
21809,False,False,False,False,False,False,False,False,False,False
21810,False,False,False,False,False,False,False,False,False,False
21811,False,False,False,False,False,False,False,False,False,False
21812,False,False,False,False,False,False,False,False,False,False
21813,False,False,False,False,False,False,False,False,False,False
21814,False,False,False,False,False,False,False,False,False,False
21815,False,False,False,False,False,False,False,False,False,False
21816,False,False,False,False,False,False,False,False,False,False
21817,False,False,False,False,False,False,False,False,False,False
21818,False,False,False,False,False,False,False,False,False,False
21819,False,False,False,False,False,False,False,False,False,False
21820,False,False,False,False,False,False,False,False,False,False
21821,False,False,False,False,False,False,False,False,False,False
21822,False,False,False,False,False,False,False,False,False,False
21823,False,False,False,False,False,False,False,False,False,False
21824,False,False,False,False,False,False,False,False,False,False
21825,False,False,False,False,False,False,False,False,False,False

In [6]:
data.notnull()

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
21796,True,True,True,True,True,True,True,True,True,True
21797,True,True,True,True,True,True,True,True,True,True
21798,True,True,True,True,True,True,True,True,True,True
21799,True,True,True,True,True,True,True,True,True,True
21800,True,True,True,True,True,True,True,True,True,True
21801,True,True,True,True,True,True,True,True,True,True
21802,True,True,True,True,True,True,True,True,True,True
21803,True,True,True,True,True,True,True,True,True,True
21804,True,True,True,True,True,True,True,True,True,True
21805,True,True,True,True,True,True,True,True,True,True
21806,True,True,True,True,True,True,True,True,True,True
21807,True,True,True,True,True,True,True,True,True,True
21808,True,True,True,True,True,True,True,True,True,True
21809,True,True,True,True,True,True,True,True,True,True
21810,True,True,True,True,True,True,True,True,True,True
21811,True,True,True,True,True,True,True,True,True,True
21812,True,True,True,True,True,True,True,True,True,True
21813,True,True,True,True,True,True,True,True,True,True
21814,True,True,True,True,True,True,True,True,True,True
21815,True,True,True,True,True,True,True,True,True,True
21816,True,True,True,True,True,True,True,True,True,True
21817,True,True,True,True,True,True,True,True,True,True
21818,True,True,True,True,True,True,True,True,True,True
21819,True,True,True,True,True,True,True,True,True,True
21820,True,True,True,True,True,True,True,True,True,True
21821,True,True,True,True,True,True,True,True,True,True
21822,True,True,True,True,True,True,True,True,True,True
21823,True,True,True,True,True,True,True,True,True,True
21824,True,True,True,True,True,True,True,True,True,True
21825,True,True,True,True,True,True,True,True,True,True

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21826 entries, 0 to 21825
Data columns (total 10 columns):
Unnamed: 0    21826 non-null int64
Tipo          21826 non-null object
Bairro        21826 non-null object
Quartos       21826 non-null int64
Vagas         21826 non-null int64
Suites        21826 non-null int64
Area          21826 non-null int64
Valor         21826 non-null float64
Condominio    21826 non-null float64
IPTU          21826 non-null float64
dtypes: float64(3), int64(5), object(2)
memory usage: 1.7+ MB

In [8]:
data['Valor'].isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
21796    False
21797    False
21798    False
21799    False
21800    False
21801    False
21802    False
21803    False
21804    False
21805    False
21806    False
21807    False
21808    False
21809    False
21810    False
21811    False
21812    False
21813    False
21814    False
21815    False
21816    False
21817    False
21818    False
21819    False
21820    False
21821    False
21822    False
21823    False
21824    False
21825    False
Name: Valor, Length: 21826, dtype: bool

In [9]:
A = data.shape[0]
data.dropna(subset = ['Valor'], inplace = True)
B = data.shape[0]
A-B

0

In [10]:
data[data['Valor'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU]
Index: []

## Tratamento de Dados Faltantes (Cont.)

In [11]:
selecao = (data['Tipo'] == 'Apartamento') & (data['Condominio'].isnull())

In [12]:
A = data.shape[0]
data = data[~selecao]
B = data.shape[0]
A - B

0

In [13]:
data[data['Condominio'].isnull()].shape[0]

0

In [14]:
data = data.fillna({'Condominio': 0, 'IPTU':0})

In [15]:
data[data['Condominio'].isnull()].shape[0]

0

In [16]:
data[data['IPTU'].isnull()].shape[0]

0

In [18]:
data.to_csv('data/aluguel_residencial.csv', sep = ';', index = False)